isKafka: true
gopath: D:/source/gopath
mysql:
  isUpdate: true
  sqlpath: /D/source/gopath/src/test-db
  envs:
    - MYSQL_ROOT_PASSWORD=1234
    - MYSQL_DATABASE_1=catalog
    - MYSQL_DATABASE_2=sync-msl-taobao
project: 
  name: sync-msl-taobao
  ports:
    - 9040:8080
  envs: 
    - APP_ENV=local
    - OUTER_TEMP_TOKEN=A0y2JxQy7ibq2hOwTsqsteOfWb7pqARy
    - APPSECRET_ENV=sandboxbed79ba1720d59717ef7d56e5
    - MSL_TAOBAO_CONN=root:1234@tcp(10.202.101.43:3306)/sync-msl-taobao?charset=utf8&parseTime=True&loc=UTC
    - TAOBAO_STOCK_CRON=@every 10m
    - TAOBAO_SLEEP=100
    - ENABLE_LOG=true
    - ENABLE_AUTO_ADJUST=false
    - REDIS_AUTH=eland2swzl
    - SMART_SESSION=EE=610120938e8d4cff21f46c6131ddc37b4329cff1818d0e92649119619
    - APPSECRET_Wisdom_ENV=23414e054cf7ad1f285158c733d4ea95
subProjects: 
  -
    name: catalog
    ports:
      - 54102:5000
      - 54202:6000
    envs: 
      - POS_ENV=local
      - JWT_SECRET=Z2tza3NsYWRtbDAxMjM0ZWhkbnRsYTk4