gopath: D:\source\gopath
iskafka: true
mysql:
  databases:
  - MYSQL_DATABASE_1=ipay
  - MYSQL_DATABASE_2=ibill
  ports:
  - 3306:3306
project:
  name: ibill-api
  gitshortpath: ipay/ibill-api
  envs:
  - APP_ENV=test
  - IBILL_CONN=root:1234@tcp(test-mysql:3306)/ibill?charset=utf8&parseTime=True&loc=UTC
  - IPAY_CONN=root:1234@tcp(test-mysql:3306)/ipay?charset=utf8&parseTime=True&loc=UTC
  - JWT_SECRET=Z2tza3NsYWRtbDAxMjM0ZWhkbnRsYTk4
  isprojectkafka: true
  ports:
  - 50505:8080
  databases:
  - ipay
  - ibill
  subnames:
  - ipay-api
  subprojects:
  - name: ipay-api
    gitshortpath: ipay/ipay-api
    envs:
    - APP_ENV=test
    - IPAY_HOST=root:1234@tcp(test-mysql:3306)/ibill?charset=utf8&parseTime=True&loc=UTC
    - IPAY_CONN=root:1234@tcp(test-mysql:3306)/ipay?charset=utf8&parseTime=True&loc=UTC
    - JWT_SECRET=Z2tza3NsYWRtbDAxMjM0ZWhkbnRsYTk4
    - WX_NOTIFY_EVENT="https://www.baidu.com"
    isprojectkafka: true
    ports:
    - 50277:8080
    databases:
    - ipay
    subnames: []
    subprojects: []
updatedscope: ALL
