services:
  ibill-api:
    build:
      context: D:\source\gopath/src/ibill-api
      dockerfile: Dockerfile
    container_name: test-ibill-api
    depends_on:
    - ipay-api
    - kafkaserver
    - mysqlserver
    environment:
    - APP_ENV=test
    - IBILL_CONN=root:1234@tcp(test-mysql:3306)/ibill?charset=utf8&parseTime=True&loc=UTC
    - IPAY_CONN=root:1234@tcp(test-mysql:3306)/ipay?charset=utf8&parseTime=True&loc=UTC
    - JWT_SECRET=Z2tza3NsYWRtbDAxMjM0ZWhkbnRsYTk4
    image: test-ibill-api
    ports:
    - 50505:8080
    restart: on-failure:5
  ipay-api:
    build:
      context: D:\source\gopath/src/ipay-api
      dockerfile: Dockerfile
    container_name: test-ipay-api
    depends_on:
    - mysqlserver
    environment:
    - APP_ENV=test
    - IPAY_HOST=root:1234@tcp(test-mysql:3306)/ibill?charset=utf8&parseTime=True&loc=UTC
    - IPAY_CONN=root:1234@tcp(test-mysql:3306)/ipay?charset=utf8&parseTime=True&loc=UTC
    - JWT_SECRET=Z2tza3NsYWRtbDAxMjM0ZWhkbnRsYTk4
    - WX_NOTIFY_EVENT="https://www.baidu.com"
    image: test-ipay-api
    ports:
    - 50277:8080
    restart: on-failure:5
  kafkaserver:
    container_name: test-kafka
    environment:
    - ADVERTISED_HOST=kafkaserver
    - ADVERTISED_PORT=9092
    hostname: kafkaserver
    image: spotify/kafka:latest
    ports:
    - 2181:2181
    - 9092:9092
    restart: always
  mysqlserver:
    container_name: test-mysql
    environment:
    - MYSQL_DATABASE_1=ipay
    - MYSQL_DATABASE_2=ibill
    - MYSQL_ROOT_PASSWORD=1234
    image: gruppometasrl/mysql57
    ports:
    - 3306:3306
    restart: always
    volumes:
    - .:/docker-entrypoint-initdb.d
version: "3"
